### PR TITLE
Requestdata likes

### PR DESCRIPTION
**Pull request by natemago**
Requestdata requests for data support for likes.

### CODE REVIEW

**Comment by anatrajkovska** [comment]
@natemago The like button does not appear where it suppose to. Can you please check if there are any extra steps that need to be taken in order for this to work?

Also please note that while testing, I have noticed that if we set these two extensions in this order -> `ckan.plugins = ... likes requestdata ...` in the .ini file, the table `user_likes_requests` won't be created and the following error is shown: 

`sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'user_likes_requests.request_id' could not find table 'ckanext_requestdata_requests' with which to generate a foreign key to target column 'id' `

**Comment by natemago** [comment]
The button won't appear probably because the blocks in requestdata are not set. The blocks are defined in a specific branch - see PR https://github.com/keitaroinc/ckanext-requestdata/pull/2
The button should appear after that PR is in place in requestdata.

About the exception, that is expected because we reference a table defined in requestdata. Possibly we can fix this by adding check if requestdata is defined.

**Comment by natemago** [comment]
The order of the two extensions matters - we must load likes first so we can override the templates in requestdata propery. 
Hold the PR for now, I'll add checks for requestdata tables.

**Comment by natemago** [comment]
Added fix for the problems. Please check again.

**Review by anatrajkovska — APPROVED** [review]

**Pull request merged**
